name: CI/CD
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
          registry-url: https://registry.npmjs.org/
      - name: Copy source
        if: github.ref == 'refs/heads/master'
        run: |
          rm -r ./simon-ui/src/
          cp -r ./exemple/src/simon-ui ./simon-ui/
          mv ./simon-ui/simon-ui ./simon-ui/src/
      - name: Publish New Major Version
        if: github.ref == 'refs/heads/master' && contains(github.event.head_commit.message, '[major]')
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          cd simon-ui
          yarn
          yarn version --new-version major --no-git-tag-version
          yarn publish
          cd ..
          git config --local user.email "simonboisset.dev@gmail.com"
          git config --local user.name "simonboisset"
          git add .
          git commit -m "New version"
          git push
      - name: Publish New Minor Version
        if: github.ref == 'refs/heads/master' && contains(github.event.head_commit.message, '[minor]')
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          cd simon-ui
          yarn
          yarn version --new-version minor --no-git-tag-version
          yarn publish
          cd ..
          git config --local user.email "simonboisset.dev@gmail.com"
          git config --local user.name "simonboisset"
          git add .
          git commit -m "New version"
          git push
      - name: Publish New Patch Version
        if: github.ref == 'refs/heads/master' && !contains(github.event.head_commit.message, '[major]') && !contains(github.event.head_commit.message, '[minor]')
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          cd simon-ui
          yarn
          yarn version --new-version patch --no-git-tag-version
          yarn publish
          cd ..
          git config --local user.email "simonboisset.dev@gmail.com"
          git config --local user.name "simonboisset"
          git add .
          git commit -m "New version"
          git push
      - name: Checkout dev
        uses: actions/checkout@v2
        if: github.ref == 'refs/heads/master'
        with:
          ref: 'dev'
      - name: Rebase Dev
        if: github.ref == 'refs/heads/master'
        run: |
          git pull origin master
          git rebase remotes/origin/master
          git push
